// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: common.proto

package proto_build

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Pager) Validate() error {
	return nil
}
func (this *CommonResponse) Validate() error {
	return nil
}
