// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: common.proto

package proto_build

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *ImageInfo) Validate() error {
	if !(this.Width > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Width", fmt.Errorf(`value '%v' must be greater than '0'`, this.Width))
	}
	if !(this.Height > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Height", fmt.Errorf(`value '%v' must be greater than '0'`, this.Height))
	}
	return nil
}
func (this *Pager) Validate() error {
	return nil
}
func (this *CommonResponse) Validate() error {
	return nil
}
func (this *UploadImageRequest) Validate() error {
	return nil
}
func (this *UploadImageResponse) Validate() error {
	return nil
}
