// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: message.proto

package proto_build

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *TextMessage) Validate() error {
	return nil
}
func (this *LocationMessage) Validate() error {
	return nil
}
func (this *FaceMessage) Validate() error {
	return nil
}
func (this *SoundMessage) Validate() error {
	return nil
}
func (this *ImageMessageItem) Validate() error {
	return nil
}
func (this *ImageMessage) Validate() error {
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *FileMessage) Validate() error {
	return nil
}
func (this *VideoMessage) Validate() error {
	return nil
}
