// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user.proto

package proto_build

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	regexp "regexp"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *User) Validate() error {
	if this.CreatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CreatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CreatedAt", err)
		}
	}
	if this.UpdatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UpdatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UpdatedAt", err)
		}
	}
	if this.DeletedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.DeletedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("DeletedAt", err)
		}
	}
	return nil
}

var _regex_CreateUserRequest_Nickname = regexp.MustCompile(`^[a-z0-9]{2,30}$`)
var _regex_CreateUserRequest_Password = regexp.MustCompile(`^[a-z][a-z0-9]{1,17}$`)
var _regex_CreateUserRequest_PasswordRpt = regexp.MustCompile(`^[a-z][a-z0-9]{1,17}$`)

func (this *CreateUserRequest) Validate() error {
	if !_regex_CreateUserRequest_Nickname.MatchString(this.Nickname) {
		return github_com_mwitkow_go_proto_validators.FieldError("Nickname", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-z0-9]{2,30}$"`, this.Nickname))
	}
	if !_regex_CreateUserRequest_Password.MatchString(this.Password) {
		return github_com_mwitkow_go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-z][a-z0-9]{1,17}$"`, this.Password))
	}
	if !_regex_CreateUserRequest_PasswordRpt.MatchString(this.PasswordRpt) {
		return github_com_mwitkow_go_proto_validators.FieldError("PasswordRpt", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-z][a-z0-9]{1,17}$"`, this.PasswordRpt))
	}
	return nil
}
func (this *CreateUserResponse) Validate() error {
	if this.User != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.User); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("User", err)
		}
	}
	return nil
}
func (this *GetUserRequest) Validate() error {
	if !(this.Id > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Id", fmt.Errorf(`value '%v' must be greater than '0'`, this.Id))
	}
	return nil
}
func (this *GetUserResponse) Validate() error {
	if this.User != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.User); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("User", err)
		}
	}
	return nil
}
func (this *QueryUserRequest) Validate() error {
	if !(this.Page > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Page", fmt.Errorf(`value '%v' must be greater than '0'`, this.Page))
	}
	if !(this.PageSize > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("PageSize", fmt.Errorf(`value '%v' must be greater than '0'`, this.PageSize))
	}
	return nil
}
func (this *QueryUserResponse) Validate() error {
	if this.Pager != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Pager); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Pager", err)
		}
	}
	for _, item := range this.User {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("User", err)
			}
		}
	}
	return nil
}
